baseURL = 'https://thehecklers.com/'
languageCode = 'en-US'
title = 'Hecklers in Development'
theme = "hugo-casper3"

disqusShortname = "thehecklers-com"
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true
publishDir      = "docs"

[params]
  title         = "Hecklers in Development: Brewing stronger Java"
  subtitle      = "Converting coffee to code, one cup at a time (but in rapid succession)"
  copyright     = "© 2018-2022"

  #feature_image = "/images/MHBetweenTwoCloudLayersWSun.jpg"
  feature_image = "/images/virtual-keyboard_dark2.jpg"
  cover         = "/images/virtual-keyboard_dark2.jpg"
  description   = "Converting coffee to code, one cup at a time (but in rapid succession)"
  RSSLink = ""

  twitter = "mkheck"
  facebook = "markhecklerdev"
  github = "mkheck"
  linkedin = "markheckler"

  orgName = "HM"
  orgWebsite = "https://www.thehecklers.com"
  orgDescription = "Connecting code to demonstrable business value"

  showSupport = true

  author = "Mark Heckler"
  authorAvatar = "/images/MarkHecklerProfilePic.jpg"
  authorLocation = "St. Louis, Redmond, the sky"
  authorWebsite = "https://thehecklers.com"
  authorDescription = "Computer scientist, software developer, licensed pilot"

  pageNotFoundTitle = "404 - Page not found"

  mainSections = ['posts', 'docs']

[permalinks]
  post = "/posts/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 150

[[menu.main]]
  name = "Abstracts"
  url = "/pages/abstracts"
  weight = 180

[[menu.main]]
  name = "Contact"
  url = "/pages/contact"
  weight = 170

[[menu.main]]
  name = "About"
  url = "/pages/about"
  weight = 160

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
