baseURL = "https://thehecklers.com/"
baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "mkheck"
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Hecklers in Development, brewing stronger Java"
  subtitle    = "Converting coffee to code, one cup at a time (but in rapid succession)"
  copyright   = "© 2018, 2019"

  cover       = "img/virtual-keyboard_dark2.jpg"
  description = "Converting coffee to code, one cup at a time (but in rapid succession)"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "mkheck"
  fbName = "markhecklerdev"
  githubName = "mkheck"
  linkedinName = "markheckler"
  mediumName = ""

  logo = ""
  orgName = "HM"
  orgWebsite = "https://www.thehecklers.com"
  orgDescription = "Connecting code to demonstrable business value"

  showSupport = true

  author = "Mark Heckler"
  authorAvatar = "img/MarkHecklerProfilePic.jpg"
  authorLocation = "St. Louis, San Francisco, Hell's Kitchen, Gallifrey"
  authorWebsite = "https://thehecklers.com"
  authorDescription = "Computer scientist & software developer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Abstracts"
  url = "/page/abstracts"
  weight = 180

[[menu.main]]
  name = "Contact me"
  url = "/page/contact"
  weight = 170

[[menu.main]]
  name = "Upcoming events"
  url = "/page/events"
  weight = 160

[[menu.main]]
  name = "Java"
  url = "/tags/java/"
  weight = 100

[[menu.main]]
  name = "Spring"
  url = "/tags/spring/"
  weight = 99

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 98

[[menu.main]]
  name = "Spring Central"
  url = "https://spring.io/"
  weight = 95


